### ISSUE TITLE
how do you use this?

### ISSUE THREAD

**Issue by ageorgios** [redelva/homebridge-broadlink-http#1]
hello! I think I want to do the same thing that you are doing.
are you using a python server or is this standalone?

**Comment by redelva** [comment]
It has to work with a Android app named Broadlink RM Bridge(https://play.google.com/store/apps/details?id=us.originally.tasker)

It will offer a funciton named Http Bridge. Simplely an api server for broadlink device.

You can open http://yourandroiddeviceip:port to get http url（try url/devices and url/codes）.

Next, edit your config.json and work with Homebridge(I am using a Raspberry pi to run homebridge).

Make sure your android device is always online.

发送自 Windows 10 版邮件应用

发件人: ageorgios
发送时间: 2017年2月28日 16:29
收件人: redelva/homebridge-broadlink-http
抄送: Subscribed
主题: [redelva/homebridge-broadlink-http] how do you use this? (#1)

hello! I think I want to do the same thing that you are doing.
are you using a python server or is this standalone?

**Comment by sansat7** [comment]
Hi, a sample config.json for you how to add two accessory": "Broadlink

**Comment by redelva** [comment]
i am using resp pi to run homebridge and  a plugin to offer api and work with broadlink.

发自我的 iPhone
